version: 1.0.{build}

os: Windows Server 2012 R2

clone_folder: c:\gopath\src\github.com\runner-mei\GoBatis

environment:
  GOPATH: c:\gopath
  GOVERSION: 110
  GO111MODULE: off
  SQLINSTANCE: SQL2012SP1
  HOST: localhost
  SQLUSER: sa
  SQLPASSWORD: Password12!
  DATABASE: test

stack: go 1.10

services:
  - mssql2012sp1

before_test:
  - go get golang.org/x/tools/cmd/goimports
  - go install golang.org/x/tools/cmd/goimports
  - go get github.com/aryann/difflib
  - go get github.com/grsmv/inflect
  - go get github.com/Knetic/govaluate
  # setup SQL Server 
  - ps: |
      $instanceName = $env:SQLINSTANCE
      Start-Service "MSSQL`$$instanceName"
      Start-Service "SQLBrowser"
  - sqlcmd -S "(local)\%SQLINSTANCE%" -Q "Use [master]; CREATE DATABASE test COLLATE Chinese_PRC_CI_AS"

test_script:
  - set PATH=%PATH%;c:\gopath\bin
  - cd c:\gopath\src\github.com\runner-mei\GoBatis\cmd\gobatis
  - go install
  - cd ../..
  - go install
  - go generate ./...
  - del gentest\fail\interface.gobatis.go
  - go test -v -dbDrv=mssql    "-dbURL=sqlserver://sa:Password12!@localhost/%SQLINSTANCE%?database=test&connection+timeout=30" ./...

build: off 