package protocol

import "fmt"

type StatusCode uint8

func (code StatusCode) Error() string {
	switch code {
	case RAKP_STATUS_NO_ERRORS:
		return "NO ERRORS"
	case RAKP_STATUS_INSUFFICIENT_RESOURCES_FOR_SESSION:
		return "INSUFFICIENT_RESOURCES_FOR_SESSION"
	case RAKP_STATUS_INVALID_SESSION_ID:
		return "INVALID_SESSION_ID"
	case RAKP_STATUS_INVALID_PAYLOAD_TYPE:
		return "INVALID_PAYLOAD_TYPE"
	case RAKP_STATUS_INVALID_AUTHENTICATION_ALGORITHM:
		return "INVALID_AUTHENTICATION_ALGORITHM:"
	case RAKP_STATUS_INVALID_INTEGRITTY_ALGORITHM:
		return "INVALID_INTEGRITTY_ALGORITHM"
	case RAKP_STATUS_NO_MATCHING_AUTHENTICATION_PAYLOAD:
		return "NO_MATCHING_AUTHENTICATION_PAYLOAD"
	case RAKP_STATUS_NO_MATCHING_INTEGRITY_PAYLOAD:
		return "NO_MATCHING_INTEGRITY_PAYLOAD"
	case RAKP_STATUS_INACTIVE_SESSION_ID:
		return "INACTIVE_SESSION_ID"
	case RAKP_STATUS_INVALID_ROLE:
		return "INVALID_ROLE"
	case RAKP_STATUS_UNAUTHORIZED_ROLE_REQUESTED:
		return "UNAUTHORIZED_ROLE_REQUESTED"
	case RAKP_STATUS_INSUFFICIENT_RESOURCES_FOR_ROLE:
		return "INSUFFICIENT_RESOURCES_FOR_ROLE"
	case RAKP_STATUS_INVALID_NAME_LENGTH:
		return "INVALID_NAME_LENGTH"
	case RAKP_STATUS_UNAUTHORIZED_NAME:
		return "UNAUTHORIZED_NAME"
	case RAKP_STATUS_UNAUTHORIZED_GUID:
		return "UNAUTHORIZED_GUID"
	case RAKP_STATUS_INVALID_INTEGRITY_CHECK_VALUE:
		return "INVALID_INTEGRITY_CHECK_VALUE"
	case RAKP_STATUS_INVALID_CONFIDENTIALITY_ALGORITHM:
		return "INVALID_CONFIDENTIALITY_ALGORITHM"
	case RAKP_STATUS_NO_CIPHER_SUITE_MATCH:
		return "NO_CIPHER_SUITE_MATCH"
	case RAKP_STATUS_ILLEGAL_PARAMTER:
		return "ILLEGAL_PARAMTER"
	default:
		return fmt.Sprintf("UNKNOWN STATUS(%v)", uint(code))
	}
}

const (
	RAKP_STATUS_NO_ERRORS                          StatusCode = 0x00
	RAKP_STATUS_INSUFFICIENT_RESOURCES_FOR_SESSION StatusCode = 0x01
	RAKP_STATUS_INVALID_SESSION_ID                 StatusCode = 0x02
	RAKP_STATUS_INVALID_PAYLOAD_TYPE               StatusCode = 0x03
	RAKP_STATUS_INVALID_AUTHENTICATION_ALGORITHM   StatusCode = 0x04
	RAKP_STATUS_INVALID_INTEGRITTY_ALGORITHM       StatusCode = 0x05
	RAKP_STATUS_NO_MATCHING_AUTHENTICATION_PAYLOAD StatusCode = 0x06
	RAKP_STATUS_NO_MATCHING_INTEGRITY_PAYLOAD      StatusCode = 0x07
	RAKP_STATUS_INACTIVE_SESSION_ID                StatusCode = 0x08
	RAKP_STATUS_INVALID_ROLE                       StatusCode = 0x09
	RAKP_STATUS_UNAUTHORIZED_ROLE_REQUESTED        StatusCode = 0x0A
	RAKP_STATUS_INSUFFICIENT_RESOURCES_FOR_ROLE    StatusCode = 0x0B
	RAKP_STATUS_INVALID_NAME_LENGTH                StatusCode = 0x0C
	RAKP_STATUS_UNAUTHORIZED_NAME                  StatusCode = 0x0D
	RAKP_STATUS_UNAUTHORIZED_GUID                  StatusCode = 0x0E
	RAKP_STATUS_INVALID_INTEGRITY_CHECK_VALUE      StatusCode = 0x0F
	RAKP_STATUS_INVALID_CONFIDENTIALITY_ALGORITHM  StatusCode = 0x10
	RAKP_STATUS_NO_CIPHER_SUITE_MATCH              StatusCode = 0x11
	RAKP_STATUS_ILLEGAL_PARAMTER                   StatusCode = 0x12
)
